import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Сайт БПФ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <main className="mx-auto flex min-h-screen max-w-xl flex-col p-6 space-y-6">
          {children}
          <footer className="text-sm text-gray-500 flex items-center justify-center gap-2">
            <p>© {new Date().getFullYear()} BPF Club</p>
            <span>•</span>
            <p>Performance is our religion</p>
          </footer>
        </main>
      </body>
    </html>
  );
}
